import type { Metadata } from 'next';
import './globals.css';

import { Nunito } from 'next/font/google';
import { EventsProvider } from '@/context/EventContext';
import { UserProvider } from '@/context/UserContext';
import { ClinicProvider } from '@/context/ClinicContext';
import { Toaster } from '@/components/ui/sonner';
import { DoctorPriver } from '@/context/DoctorContext';
import { PlansProvider } from '@/context/PlansContext';
import { DocumentsProvider } from '@/context/DocumentContext';
import { SelectDoctorProvider } from '@/context/SelectDoctor';
import { WaitEventProvider } from '@/context/WaitEventContext';
import { CalendarViewTypeProvider } from '@/context/CalendarViewType';

const font = Nunito({
	subsets: ['latin'],
	weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
	title: 'ProClinic - Medical Records',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='pt-br' className=''>
			<link rel='icon' href='/favicon.ico' sizes='any' />
			<body className={`${font.className} antialiased`}>
				<UserProvider>
					<ClinicProvider>
						<DoctorPriver>
							<EventsProvider>
								<WaitEventProvider>
									<PlansProvider>
										<SelectDoctorProvider>
											<DocumentsProvider>
												<CalendarViewTypeProvider>{children}</CalendarViewTypeProvider>
											</DocumentsProvider>
											<Toaster />
										</SelectDoctorProvider>
									</PlansProvider>
								</WaitEventProvider>
							</EventsProvider>
						</DoctorPriver>
					</ClinicProvider>
				</UserProvider>
			</body>
		</html>
	);
}
